### ISSUE TITLE
Implement tax engine

### ISSUE THREAD

**Issue by RestitutorOrbis** [RestitutorOrbis/finsim#3]
# Why?

Build out a system for supporting tax calculations in the simulation. Since, I'm a software engineer it probably makes sense to focus on jurisdictions in Canada that I as a software engineer am likely to spend time in. America can be handled later.

# TODO
 - [x] Implement progressive income tax
 - [x] Implement flexible deductions system
 - [ ] Figure out what tax credits are worth representing
 - [x] Validate currencies in tax bracket
 - [x] Make `deductions_map` internal in `TaxRegime`
 - [x] Validate currencies in `TaxRegime`
 - [x] Correct variable names throughout current implementation
 - [x] Use thiserror and unify errors that can occur in tax calculator
 - [x] Implement ordering on tax brackets
 - [ ] Replace tax credit enum with String and then have an enum at the country/province level to force certain inputs
 - [ ] Build out ability to handle parallel tax regimes (ex. Ontario income tax + federal income tax + Ontario health premium)
 - [ ] Add more comprehensive test suite
 - [ ] Add tax regime generator system for easily building out tax regimes
 - [ ] Implement federal tax regime
 - [ ] Implement BC tax regime
 - [ ] Implement Alberta tax regime
 - [ ] Implement Ontario tax regime
 - [ ] Implement Quebec tax regime
