### ISSUE TITLE
Implement portfolio

### ISSUE THREAD

**Issue by RestitutorOrbis** [RestitutorOrbis/finsim#4]
# Why?

A financial simulation is impossible to build without the notion of a portfolio. A portfolio provides a mechanism to model the growth of one's capital assets. To model this properly, we need to also model assets, inflation, and registered accounts. To be clear here, registered accounts refers to special accounts with unique properties. The two target account types that are relevant for this ticket are the TFSA and the RRSP which are crucial tools for Canadian financial planning.

# TODO
- [ ] Implement concept of assets (ex. equities, bonds)
- [ ] Implement concept of growth of assets over time (ex. modelling the historical growth rate of stocks)
- [ ] Implement inflation
- [ ] Implement notion of accounts
- [ ] Implement notion of a portfolio which is just a collection of accounts
