### ISSUE TITLE
Implement events

### ISSUE THREAD

**Issue by RestitutorOrbis** [RestitutorOrbis/finsim#5]
# Why?

One's finances are affected by events. These events can include bi-weekly salary cheques, dividends, rent payments, and more. There are generally two types of events for our purposes, income events and expense events. For the simulation, there will be the notion of event streams which will generate an event for a particular day if it matches certain conditions. I'm also looking to implement the notion of scheduled events within the simulation.

# TODO

- [ ] Implement event streams
- [ ] Implement scheduled events
- [ ] Distinguish between income events and expense events
- [ ] Model changes in the events produced by an event stream over time (ex. model annual rent increases)
